post http://localhost:3000/user-api/register
Content-Type: application/json

{
    "username": "sreya",
    "email":"sreya@mail.com",
    "password":"sreya",
    "role": "customer",
    "address":[]
}

### login 
post http://localhost:3000/user-api/user-login
Content-Type:  application/json

{
    "username":"sreya",
    "password":"sreya"
}
### get all books
get http://localhost:3000/book-api/books

